routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::middleware(['auth', 'superadmin'])
    ->group(function () {
        Route::get('/superadmin', [App\Http\Controllers\SuperAdmin\DashboardController::class, 'index'])->name('dashboard');
        Route::resource('superadmin-cabang', 'App\Http\Controllers\SuperAdmin\Master\CabangController');
        Route::resource('superadmin-user', 'App\Http\Controllers\SuperAdmin\Master\UserController');
        Route::resource('superadmin-divisi', 'App\Http\Controllers\SuperAdmin\Master\DivisiController');
        Route::resource('superadmin-jabatan', 'App\Http\Controllers\SuperaAmin\Master\JabatanController');
        Route::get('/superadmin-karyawan', [App\Http\Controllers\SuperAdmin\Master\KaryawanController::class, 'index'])->name('superadmin.karyawan');
        Route::get('/superadmin-karyawan-tambah', [App\Http\Controllers\SuperAdmin\Master\KaryawanController::class, 'create'])->name('superadmin.karyawan-tambah');
        Route::post('/superadmin-karyawan-store', [App\Http\Controllers\SuperAdmin\Master\KaryawanController::class, 'store'])->name('superadmin.karyawan-store');
        Route::get('/superadmin-karyawan-edit/{id?}', [App\Http\Controllers\SuperAdmin\Master\KaryawanController::class, 'edit'])->name('superadmin.karyawan-edit');
        Route::put('/superadmin-karyawan-update/{id?}', [App\Http\Controllers\SuperAdmin\Master\KaryawanController::class, 'update'])->name('superadmin.karyawan-update');
    });

Route::middleware(['auth', 'admin'])
    ->group(function () {
        Route::get('/admin', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
        Route::resource('admin-user', 'App\Http\Controllers\Admin\Master\UserController');
        Route::get('/admin-karyawan', [App\Http\Controllers\Admin\Master\KaryawanController::class, 'index'])->name('admin.karyawan');
        Route::get('/admin-karyawan-tambah', [App\Http\Controllers\Admin\Master\KaryawanController::class, 'create'])->name('admin.karyawan-tambah');
        Route::post('/admin-karyawan-store', [App\Http\Controllers\Admin\Master\KaryawanController::class, 'store'])->name('admin.karyawan-store');
        Route::get('/admin-karyawan-edit/{id?}', [App\Http\Controllers\Admin\Master\KaryawanController::class, 'edit'])->name('admin.karyawan-edit');
        Route::put('/admin-karyawan-update/{id?}', [App\Http\Controllers\Admin\Master\KaryawanController::class, 'update'])->name('admin.karyawan-update');
        Route::resource('admin-user', 'App\Http\Controllers\Admin\Master\UserController');
        Route::resource('admin-divisi', 'App\Http\Controllers\Admin\Master\DivisiController');
        Route::resource('admin-jabatan', 'App\Http\Controllers\Admin\Master\JabatanController');
    });

Route::middleware(['auth', 'cabang'])
    ->group(function () {
        Route::get('/cabang', [App\Http\Controllers\Cabang\DashboardController::class, 'index'])->name('cabang.dashboard');
        Route::resource('cabang-user', 'App\Http\Controllers\Cabang\Master\UserController');
        Route::get('/cabang-karyawan', [App\Http\Controllers\Cabang\Master\KaryawanController::class, 'index'])->name('cabang.karyawan');
        Route::get('/cabang-karyawan-tambah', [App\Http\Controllers\Cabang\Master\KaryawanController::class, 'create'])->name('cabang.karyawan-tambah');
        Route::post('/cabang-karyawan-store', [App\Http\Controllers\Cabang\Master\KaryawanController::class, 'store'])->name('cabang.karyawan-store');
        Route::get('/cabang-karyawan-edit/{id?}', [App\Http\Controllers\Cabang\Master\KaryawanController::class, 'edit'])->name('cabang.karyawan-edit');
        Route::put('/cabang-karyawan-update/{id?}', [App\Http\Controllers\Cabang\Master\KaryawanController::class, 'update'])->name('cabang.karyawan-update');
    });

app/Models/Cabang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cabang extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/Admin/Master/CabangController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Cabang;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use RealRashid\SweetAlert\Facades\Alert;


use App\Http\Requests\admin\CabangRequest;

class CabangController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $cabang = Cabang::where('active', 1)->get();
        $user = Auth::user();
        return view('pages.admin.master.cabang.dashboard', [
            'cabang' => $cabang,
            'user' => $user
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.admin.master.cabang.tambah');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->nama_cabang);
        $data['active'] = 1;

        Cabang::create($data);
        toast('Cabang berhasil ditambahkan!', 'success');
        return redirect()->route('admin-cabang.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Request $request, string $id)
    {
        $item = Cabang::where('id', $id)->first();
        $data['active'] = 0;
        $item->update($data);

        return redirect()->route('admin-cabang.index');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $item = Cabang::where('slug', $id)->first();
        $user = Auth::user();
        return view('pages.admin.master.cabang.edit', [
            'item' => $item,
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->nama_cabang);
        $data['active'] = 1;

        $item = Cabang::findOrFail($id);
        $item->update($data);
        toast('Cabang berhasil diupdate!', 'success');
        return redirect()->route('admin-cabang.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
    }
}

app/Http/Controllers/Admin/Master/DivisiController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Divisi;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class DivisiController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $divisi = Divisi::where('active', 1)->get();
        $user = Auth::user();
        return view('pages.admin.master.divisi.dashboard', [
            'divisi' => $divisi,
            'user' => $user
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.admin.master.divisi.tambah');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->nama_divisi);
        $data['active'] = 1;

        Divisi::create($data);
        toast('Divisi berhasil ditambahkan!', 'success');
        return redirect()->route('admin-divisi.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $item = Divisi::where('id', $id)->first();
        $data['active'] = 0;
        $item->update($data);

        return redirect()->route('admin-divisi.index');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $item = Divisi::where('slug', $id)->first();

        return view('pages.admin.master.divisi.edit', [
            'item' => $item,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->nama_divisi);
        $data['active'] = 1;

        $item = Divisi::findOrFail($id);
        $item->update($data);
        toast('Divisi berhasil diupdate!', 'success');
        return redirect()->route('admin-divisi.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Admin/Master/JabatanController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Jabatan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $jabatan = Jabatan::where('active', 1)->get();
        $user = Auth::user();
        return view('pages.admin.master.jabatan.dashboard', [
            'jabatan' => $jabatan,
            'user' => $user
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.admin.master.jabatan.tambah');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->nama_jabatan);
        $data['active'] = 1;

        Jabatan::create($data);
        toast('Jabatan berhasil ditambahkan!', 'success');
        return redirect()->route('admin-jabatan.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $item = Jabatan::where('id', $id)->first();
        $data['active'] = 0;
        $item->update($data);

        return redirect()->route('admin-jabatan.index');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $item = Jabatan::where('slug', $id)->first();

        return view('pages.admin.master.jabatan.edit', [
            'item' => $item,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->all();

        $data['slug'] = Str::slug($request->nama_divisi);
        $data['active'] = 1;

        $item = Jabatan::findOrFail($id);
        $item->update($data);
        toast('Jabatan berhasil diupdate!', 'success');
        return redirect()->route('admin-jabatan.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Admin/Master/KaryawanController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Cabang;
use App\Models\Divisi;
use App\Models\Jabatan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use RealRashid\SweetAlert\Facades\Alert;

class KaryawanController extends Controller
{
    public function index()
    {
        $user = User::where('active', 1)->get();
        return view('pages.admin.master.karyawan.dashboard', [
            'user' => $user,
        ]);
    }

    public function create()
    {
        $cabang = Cabang::where('active', 1)->get();
        $jabatan = Jabatan::where('active', 1)->get();
        $divisi = Divisi::where('active', 1)->get();
        return view('pages.admin.master.karyawan.tambah', [
            'cabang' => $cabang,
            'jabatan' => $jabatan,
            'divisi' => $divisi,
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->all();

        if ($request->password) {
            $data['password'] = bcrypt($request->password);
        } else {
            unset($data['password']);
        }

        $data['active'] = 1;
        $data['id_roles'] = 4;

        User::create($data);
        toast('Karyawan berhasil ditambahkan!', 'success');
        return redirect()->route('admin.karyawan');
    }

    public function edit(string $id)
    {
        $item = User::findOrFail($id);
        $cabang = Cabang::where('active', 1)->get();
        $jabatan = Jabatan::where('active', 1)->get();
        $divisi = Divisi::where('active', 1)->get();
        return view('pages.admin.master.karyawan.edit', [
            'item' => $item,
            'cabang' => $cabang,
            'jabatan' => $jabatan,
            'divisi' => $divisi,
        ]);
    }
    public function update(Request $request, string $id)
    {
        $data = $request->all();

        $item = User::findOrFail($id);
        if ($request->password) {
            $data['password'] = bcrypt($request->password);
        } else {
            unset($data['password']);
        }
        $item->update($data);

        toast('Karyawan berhasil diupdate!', 'success');

        return redirect()->route('admin.karyawan');
    }

    public function delete(string $id)
    {
        $item = User::where('id', $id)->first();
        $data['active'] = 0;
        $item->update($data);

        return redirect()->route('admin.karyawan');
    }
}

app/Http/Controllers/Admin/Master/UserController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user = User::where('active', 1)->get();
        return view('pages.admin.master.user.dashboard', [
            'user' => $user
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $item = User::where('id', $id)->first();
        $data['active'] = 0;
        $item->update($data);

        return redirect()->route('admin.karyawan');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $item = User::findOrFail($id);
        return view('pages.admin.master.user.edit', [
            'item' => $item,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->all();

        $item = User::findOrFail($id);
        if ($request->password) {
            $data['password'] = bcrypt($request->password);
        } else {
            unset($data['password']);
        }

        $item->update($data);

        toast('User berhasil diupdate!', 'success');
        return redirect()->route('admin.dashboard');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Cabang/DashboardController.php
<?php

namespace App\Http\Controllers\Cabang;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('pages.cabang.dashboard');
    }
}

resources/views/pages/cabang/master/cabang/dashboard.blade.php
@extends('layouts.admin')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Daftar Data Cabang</h4>
                            </div>

                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-1">
                                        <thead>
                                            <tr>
                                                <th class="text-center">
                                                    #
                                                </th>
                                                <th>Nama Cabang</th>
                                                <th>Alamat Cabang</th>
                                                <th>Status</th>
                                                <th>Aksi</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @php
                                                $no = 1;
                                            @endphp
                                            @foreach ($cabang as $item)
                                                <tr>
                                                    <td>
                                                        {{ $no++ }}
                                                    </td>
                                                    <td>{{ $item->nama_cabang }}</td>
                                                    <td>{{ $item->alamat_cabang }}</td>
                                                    <td>
                                                        @if ($item->active == 1)
                                                            <div class="badge badge-success">Aktif</div>
                                                        @else
                                                            <div class="badge badge-danger">Tidak Aktif</div>
                                                        @endif
                                                    </td>
                                                    <td><a href="{{ route('superadmin-cabang.edit', $item->slug) }}"
                                                            class="btn btn-primary">Edit Data</a>
                                                        <button class="btn btn-danger deleted"
                                                            data-id="{{ $item->id }}">Delete</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $('.deleted').click(function() {
            var id = $(this).data('id');
            swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this post!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        // var id = $(this).data('id')
                        window.location.href = "{{ route('superadmin-cabang.show', ':id') }}".replace(':id',
                        id);
                        swal('Poof! Your imaginary file has been deleted!', {
                            icon: 'success',
                        });
                    } else {
                        swal("Your post is safe!");
                    }
                });
        });
    </script>
@endsection

resources/views/pages/cabang/master/cabang/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('cabang.update', $item->id) }}" method="post"
                                enctype="multipart/form-data" class="needs-validation" novalidate="">
                                @method('PUT')
                                @csrf
                                <div class="card-header">
                                    <h4>Silahkan isi form berikut untuk edit data cabang</h4>
                                </div>
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Nama Cabang</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" value="{{ $item->nama_cabang }}"
                                                required="" name="nama_cabang">
                                            <div class="invalid-feedback">
                                                Silahkan masukkan nama cabang
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Alamat Cabang</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" required="" name="alamat_cabang"
                                                value="{{ $item->alamat_cabang }}">
                                            <div class="invalid-feedback">
                                                Silahkan masukkan alamat cabang
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/pages/cabang/master/cabang/tambah.blade.php
@extends('layouts.admin')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('cabang.store') }}" method="post" enctype="multipart/form-data"
                                class="needs-validation" novalidate="">
                                @csrf
                                <div class="card-header">
                                    <h4>Silahkan isi form berikut ubtuk menambah data cabang</h4>
                                </div>
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Nama Cabang</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" required="" name="nama_cabang">
                                            <div class="invalid-feedback">
                                                Silahkan masukkan nama cabang
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Alamat Cabang</label>
                                        <div class="col-sm-9">
                                            <textarea class="summernote-simple" name="alamat_cabang"></textarea>
                                            <div class="invalid-feedback">
                                                Silahkan masukkan alamat cabang
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-right">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection